{% set name = "tensorflow-probability" %}
{% set version = "0.7" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/tensorflow/probability/archive/v{{ version }}.tar.gz
  sha256: aa938dfb84e68e1f645a5543ed2e7eeb2bdc260f751e5a4e8434b25062b7a25f
  patches:
    - 0001-always-build-release.patch

build:
  noarch: python
  number: 1
  script: 
    - rm -f BUILD
    - "{{ PYTHON }} -m pip install . --no-deps -vv"

requirements:
  host:
    - python
    - pip
  run:
    - python
    - numpy >=1.13.3
    - six >=1.10.0
  run_constrained:
    - tensorflow >=1.13.1

test:
  commands:
  - echo "test disabled"
  # BLOCKED BY: conda-forge/tensorflow-feedstock#6
  #imports:
  #  - tensorflow_probability

about:
  home: https://www.tensorflow.org/probability/
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  summary: 'TensorFlow Probability is a library for probabilistic reasoning and statistical analysis in TensorFlow'

  description: |
    TensorFlow Probability is a library for probabilistic reasoning 
    and statistical analysis in TensorFlow. As part of the TensorFlow
    ecosystem, TensorFlow Probability provides integration of
    probabilistic methods with deep networks, gradient-based inference
    via automatic differentiation, and scalability to large datasets
    and models via hardware acceleration (e.g., GPUs) and distributed
    computation.
  doc_url: https://www.tensorflow.org/probability/overview
  dev_url: https://github.com/tensorflow/probability

extra:
  recipe-maintainers:
    - sodre
    - adbeda
