{% set name = "tensorflow-probability" %}
{% set version = "0.9.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  # Rename this to dummy since we don't want CB to extract it
  fn: tensorflow_probability-{{ version }}-py2.py3-none-any.whl.dummy  # [win]
  url: https://files.pythonhosted.org/packages/9b/ed/f587d64127bbb85e539f06a2aace1240b7b5c6b4267bea94f232230551a5/tensorflow_probability-{{ version }}-py2.py3-none-any.whl  # [win]
  sha256: 66928dcbbc12987e574232a576bd9643ba7ca6b2a837f2182417286ac955d50f                    # [win]

build:
  number: 0
  skip: True  # [not win]

requirements:
  host:
    - python
    - pip
    - setuptools
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
  run:
    - python
    - numpy >=1.13.3
    - six >=1.10.0
    - decorator
    - cloudpickle ==1.2.2
    - gast >=0.2
    - tensorflow-base ==2.1

test:
  imports:
    - tensorflow_probability

about:
  home: https://www.tensorflow.org/probability/
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  summary: 'TensorFlow Probability is a library for probabilistic reasoning and statistical analysis in TensorFlow'

  description: |
    TensorFlow Probability is a library for probabilistic reasoning 
    and statistical analysis in TensorFlow. As part of the TensorFlow
    ecosystem, TensorFlow Probability provides integration of
    probabilistic methods with deep networks, gradient-based inference
    via automatic differentiation, and scalability to large datasets
    and models via hardware acceleration (e.g., GPUs) and distributed
    computation.
  doc_url: https://www.tensorflow.org/probability/overview
  dev_url: https://github.com/tensorflow/probability

extra:
  recipe-maintainers:
    - sodre
    - adbeda
