{% set name = "tensorflow-probability" %}
{% set version = "0.25.0" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://github.com/{{ name.split('-')[0] }}/{{ name.split('-')[1] }}/archive/refs/tags/v{{ version }}.tar.gz
  sha256: 73cf3e52d3b5ee48fc919631e7fa3621849b8ce8d453017016a5148815856bc2
  patches:
    - patches/0001-Always-build-as-release.patch
    - patches/0002-fix_jax_pytype_mapping.patch
    - patches/0003-Fix-non-portable-date-utc-on-osx.patch
    - patches/0004-print-setup.py-output.patch
    - patches/0005-Fix-windows-runfiles-path.patch
    - patches/0006-rendomize-foler-where-windows-build-pip_pkg.patch

build:
  number: 0
  script:
    build:
  script:
    - bazel --max_idle_secs=1 build --copt=-O3 :pip_pkg                          # [unix]
    - mkdir -p tmp-pkg                                                           # [unix]
    - ./bazel-bin/pip_pkg tmp-pkg                                                # [unix]
    - {{ PYTHON }} -m pip install --upgrade --no-deps --no-build-isolation -vv tmp-pkg/*.whl  # [unix]
    - bazel shutdown                                                             # [win]
    - bazel --output_user_root=%TEMP%\bazel_out_%RANDOM% --max_idle_secs=1 build --copt=-O3 --enable_runfiles :pip_pkg        # [win]
    - if not exist tmp-pkg mkdir tmp-pkg                                         # [win]
    - bazel-bin\pip_pkg.exe tmp-pkg                                              # [win]
    - dir tmp-pkg                                                                # [win]
    - for %%f in (tmp-pkg\*.whl) do (%PYTHON% -m pip install --upgrade --no-deps --no-build-isolation -vv "%%f")  # [win]
    # Error: [WinError 5] Access is denied: 'Library\\bin\\server\\jvm.dll'
    - bazel shutdown                                                             # [win]
  skip: true  # [py<39]

requirements:
  build:
    - {{ stdlib('c') }}
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - absl-py
    - bazel <7
    - bazel-toolchain >=0.4.1  # [unix]
    - setuptools
  host:
    - pip
    - python
    - wheel
    - setuptools
  run:
    - python
    - absl-py
    - six >=1.10.0
    - numpy >=1.13.3
    - decorator
    - cloudpickle >=1.3
    - gast >=0.3.2
    - dm-tree
  run_constrained:
    # Optional dependencies: tensorflow and tf-keras / tensorflow-datasets
    # TensorFlow backend requires tf-keras as this package only supports Keras 2
    - tensorflow-base >=2.16.0
    - tf-keras >=2.16.0
    - tensorflow-datasets >=2.2.0

test:
  imports:
    - tensorflow_probability
  requires:
    - pip
  commands:
    - pip check

about:
  home: https://www.tensorflow.org/probability
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  summary: 'TensorFlow Probability is a library for probabilistic reasoning and statistical analysis in TensorFlow'
  description: |
    TensorFlow Probability is a library for probabilistic reasoning 
    and statistical analysis in TensorFlow. As part of the TensorFlow
    ecosystem, TensorFlow Probability provides integration of
    probabilistic methods with deep networks, gradient-based inference
    via automatic differentiation, and scalability to large datasets
    and models via hardware acceleration (e.g., GPUs) and distributed
    computation.
  doc_url: https://www.tensorflow.org/probability/overview
  dev_url: https://github.com/tensorflow/probability

extra:
  recipe-maintainers:
    - sodre
    - adbeda
