{% set name = "tensorflow-probability" %}
{% set version = "0.24.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/tensorflow/probability/archive/refs/tags/v{{ version }}.tar.gz
  sha256: 3d75418cef09ea357ee879347133ab784fe4637a5ba251a8e06ef930dd970a3e
  patches:
    - 0001-always-build-release.patch

build:
  noarch: python
  # dm-tree not available on s390x
  skip: True  # [s390x or py<36]
  number: 1
  script: 
    - rm -f BUILD
    - {{ PYTHON }} -m pip install . --no-deps --no-build-isolation -vv

requirements:
  build:
    - m2-patch  # [win]
    - patch     # [not win]
  host:
    - python
    - pip
    - setuptools
    - wheel
  run:
    - python
    - absl-py
    - six >=1.10.0
    - numpy >=1.13.3
    - decorator
    - cloudpickle >=1.3
    - gast >=0.3.2  # For autobatching
    - dm-tree  # For NumPy/JAX backends (hence, also for prefer_static)
  run_constrained:
    # https://github.com/tensorflow/probability/blob/21ce02d10112504632ff9c1d22e5cd93ec24694b/tensorflow_probability/python/__init__.py#L58-L68
    - tensorflow >=2.16
    - tensorflow-datasets >=2.2.0
    - tf-keras >=2.16

test:
  imports:
    - tensorflow_probability
  requires:
    - pip
  commands:
    - pip check

about:
  home: https://www.tensorflow.org/probability/
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  summary: 'TensorFlow Probability is a library for probabilistic reasoning and statistical analysis in TensorFlow'

  description: |
    TensorFlow Probability is a library for probabilistic reasoning 
    and statistical analysis in TensorFlow. As part of the TensorFlow
    ecosystem, TensorFlow Probability provides integration of
    probabilistic methods with deep networks, gradient-based inference
    via automatic differentiation, and scalability to large datasets
    and models via hardware acceleration (e.g., GPUs) and distributed
    computation.
  doc_url: https://www.tensorflow.org/probability/overview
  dev_url: https://github.com/tensorflow/probability

extra:
  recipe-maintainers:
    - sodre
    - adbeda
