travis:
  secure:
    BINSTAR_TOKEN: qTxr3TKX7sF1T9ogaOMjQ33RuQPMbc+KzcIRzsL/cW1qsXtZ+K2u9g+wX6s4rKPFMzBKxXZk6cLcZmuGGM6n9kjjAfbeIrWiQQ4Z6grDRs8dz1jDKiou0P9cfcPtHwhWujMjE6s8jyMo3OFyOAf27J83TP1UKOEZZUMzkz+i+pUgm0fGvrcAhr/9lGzY3t4HAb0P/7XOlZrGrHa9dluvmwFbN4jaN5ozurPu1ubKk5U/PEuoFx7FWTY0pQLrgiAXYFIGGvdCbN9TuSjDRjb36xF2UDj7DiTX0OpfDJtnPUn3y+LlkKXBN+vbumyut2GW855YWJe0zjrH1xS8fk77hQ4p2DV3678rOx8UyEaeJghc6d3RtF6Xw2Qz2qXYo61Ztn2zGH3Ft0KkRxFDRh62TvrOllyQ7atHtAIq8ncksjVYI7iZDNrPZkoujsUMSBEy+bVcdyZplZui6d7Z0Z6OmqueelNnwy8zSjkK1hTkzyKay0pTqBHsoHVhafU1gVAjdWaUt3Yqz4Q7Qq3j59Cl9i41IWyRVr1dXPub/kMBkHq+Y2HxVUYxoDaz/GeihOq+zdjXxjH8nLUJSTfAKYhvGNe/+vSRrOOQPw7XugIg/wMVkCWmZcTSI1/CoM6USoV0MCkc+/2f5c3zGp1e3K/2YTHbAKOBgpMi4Y1TdUvavuk=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
